theme: jekyll-theme-time-machine
source: .
baseurl: "/easy-xml"
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Isilex
tagline:             'Easy Collaborative XML Data Driver'
description:         'Isilex is a CMS based on Basex'
url:                 https://isilex.github.io/easy-xml/
baseurl: "/easy-xml"
paginate:            5

# About/contact
author:
  name:              DIM SDTCN
  url:               https://twitter.com/xsalvador
  email:            

# Custom vars
version:             1.0.0
